typography_spectrum: 0.9376298089046031
color:
  saturation: 0.12276237015612423
  brandStrength: 0.27285502827726305
  lightness: 0.43062383751384914
  brandColors:
    - '#F2385A'
    - '#F5A503'
    - '#E9F1DF'
    - '#4AD9D9'
    - '#36B1BF'
  rhythmicContrast: 0.42643371946178377
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4159819963388145
analytics:
  twitter: null
  google: null
  facebook: null
name: One Earth Community
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - id: 'https://testing.thegrid.io/app'
    url: 'https://testing.thegrid.io/app'
    name: Login
    type: external
  - id: 'http://thegrid.ai/justme/'
    url: 'http://thegrid.ai/justme/'
    name: Just Me & You
    type: external
  - id: 'https://thegrid.ai/myallacrossamerica/'
    url: 'https://thegrid.ai/myallacrossamerica/'
    name: My Country
    type: external
  - id: 'http://thegrid.ai/one-earth-community-blog/'
    url: 'http://thegrid.ai/one-earth-community-blog/'
    name: '"the blog"'
    type: external
  - id: 'https://thegrid.ai/one-earth-challanged/'
    url: 'https://thegrid.ai/one-earth-challanged/'
    name: 'One Earth Challenged '
    type: external
  - id: 'https://thegridai.wufoo.com/forms/zkbqkdh11mytyz/'
    url: 'https://thegridai.wufoo.com/forms/zkbqkdh11mytyz/'
    name: Support
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
