name: One Earth Community
favicon: null
layout_spectrum: 0.5009
typography_spectrum: 0.74808
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c3c3c3'
    - '#393c35'
    - '#aa6430'
    - '#fdfee0'
    - '#fcef41'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.835115
purpose: []
