typography_spectrum: 0.9017185
color:
  saturation: 0.2937701
  brandStrength: 0.03675346518866718
  lightness: 0.320623
  brandColors:
    - '#63A69F'
    - '#F2E1AC'
    - '#F2836B'
    - '#F2594B'
    - '#CD2C24'
  rhythmicContrast: 0.5239127
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7282301259692758
analytics:
  twitter: null
  google: null
  facebook: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6f561186-097f-48f0-8b5b-70fe89c90a6a.png
name: One Earth Community
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: login
    url: 'https://testing.thegrid.io/app'
    type: external
  - name: sign up
    url: 'https://thegrid.io/#46294'
    type: external
  - name: me and you
    url: 'http://thegrid.ai/justme/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8bf933f8-5958-49bb-896a-9ad2d77a2cfa.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: we all live under the same sun
description: one earth...one community
purpose: []
