title: ''
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: ''
color:
  saturation: 0.2937701
  brandStrength: 0.03675346518866718
  lightness: 0.320623
  brandColors:
    - '#63A69F'
    - '#F2E1AC'
    - '#F2836B'
    - '#F2594B'
    - '#CD2C24'
  rhythmicContrast: 0.5239127
navigation:
  - name: Login
    url: 'https://testing.thegrid.io/app'
    type: external
  - name: Join Us
    url: 'https://thegrid.io/#46294'
    type: external
  - name: Just Me & You
    url: 'http://thegrid.ai/justme/'
    type: external
  - name: My Country
    url: 'https://thegrid.ai/myallacrossamerica/'
    type: external
  - name: One Earth Community "the blog"
    url: 'http://thegrid.ai/one-earth-community-blog/'
    type: external
  - name: One Earth Challenged "the blog"
    url: 'https://thegrid.ai/one-earth-challanged/'
    type: external
  - name: Support
    url: 'https://thegridai.wufoo.com/forms/zkbqkdh11mytyz/'
    type: external
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: One Earth Community
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9017185
layout_spectrum: 0.7282301259692758
