layout_spectrum: 0.8923903
typography_spectrum: 0.8418948
color:
  saturation: 0.7554449
  lightness: 0.2251785
  brandStrength: 0.7696025
  brandColors:
    - '#B2BCC8'
    - '#22320E'
    - '#858E95'
    - '#607827'
    - '#D9E1EE'
  rhythmicContrast: 0.835115
name: One Earth Community
