layout_spectrum: 0.8077712738886476
typography_spectrum: 0.2896371001843363
color:
  saturation: 0.8494460950605571
  brandStrength: 0.1984039710368961
  rhythmicContrast: 0.4685765157919377
  brandColors:
    - '#105B63'
    - '#FFFAD5'
    - '#FFD34E'
    - '#DB9E36'
    - '#BD4932'
  lightness: 0.13749062991701066
coverPrefs:
  filter: false
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: rick o
  email: rick.yourfamilyplaces@comcast.net
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c7feb80c-77fd-4716-ac73-35e91580fa2c.png
name: One Earth Community
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: community blog
    url: 'http://thegrid.ai/one-earth-community-blog/'
    type: external
  - name: my country
    url: 'https://thegrid.ai/myallacrossamerica/'
    type: external
  - name: just me
    url: 'http://thegrid.ai/justme/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8bf933f8-5958-49bb-896a-9ad2d77a2cfa.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: we all live under the same sun
description: ''
purpose: []
