typography_spectrum: 0.07048509735614061
color:
  saturation: 0.6057318416424096
  brandStrength: 0.9695733333937824
  lightness: 0.1630346409510821
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
  rhythmicContrast: 0.32339313183911145
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6245972
analytics:
  twitter: null
  google: null
  facebook: null
name: One Earth Community
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - id: 'https://testing.thegrid.io/app'
    url: 'https://testing.thegrid.io/app'
    name: Login
    type: external
  - id: 'https://thegrid.ai/one-earth-challanged/'
    url: 'https://thegrid.ai/one-earth-challanged/'
    name: 'One Earth Challenged '
    type: external
  - id: 'https://thegrid.ai/myallacrossamerica/'
    url: 'https://thegrid.ai/myallacrossamerica/'
    name: My Country
    type: external
  - id: 'http://thegrid.ai/justme/'
    url: 'http://thegrid.ai/justme/'
    name: Just Me & You
    type: external
  - id: 'https://thegridai.wufoo.com/forms/zkbqkdh11mytyz/'
    url: 'https://thegridai.wufoo.com/forms/zkbqkdh11mytyz/'
    name: Support
    type: external
  - id: 'http://thegrid.ai/one-earth-community-blog/'
    url: 'http://thegrid.ai/one-earth-community-blog/'
    name: '"the blog"'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
