title: ''
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: ''
color:
  saturation: 0.6202811698894948
  brandStrength: 0.6688865758478642
  lightness: 0.12648301431909204
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#D2A881'
    - '#A37253'
    - '#72A2BA'
  rhythmicContrast: 0.4988510722760111
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: One Earth Community
favicon: null
navigation:
  - name: Login
    url: 'https://testing.thegrid.io/app'
    type: external
  - name: Just Me & You
    url: 'http://thegrid.ai/justme/'
    type: external
  - name: My Country
    url: 'https://thegrid.ai/myallacrossamerica/'
    type: external
  - name: One Earth Community "the blog"
    url: 'http://thegrid.ai/one-earth-community-blog/'
    type: external
  - name: One Earth Challenged "the blog"
    url: 'https://thegrid.ai/one-earth-challanged/'
    type: external
  - name: Support
    url: 'https://thegridai.wufoo.com/forms/zkbqkdh11mytyz/'
    type: external
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5196787004824728
layout_spectrum: 0.7282301259692758
