title: ''
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: ''
color:
  saturation: 0.1050340803340077
  brandStrength: 0.224048180738464
  rhythmicContrast: 0.7713874033652246
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  lightness: 0.5386176810134202
coverPrefs:
  filter: false
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8bf933f8-5958-49bb-896a-9ad2d77a2cfa.png
author:
  name: rick o
  email: rick.yourfamilyplaces@comcast.net
name: One Earth Community
opengraph:
  image: null
  type: null
  appId: null
navigation:
  - name: community blog
    url: 'http://thegrid.ai/one-earth-community-blog/'
    type: external
  - name: my country
    url: 'https://thegrid.ai/myallacrossamerica/'
    type: external
  - name: just me
    url: 'http://thegrid.ai/justme/'
    type: external
  - name: challanges...
    url: 'https://thegrid.ai/one-earth-challanged/'
    type: external
  - name: About
    id: 2e5f36fd-63cc-40a5-8054-021d3a85c04e
    type: content
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c7feb80c-77fd-4716-ac73-35e91580fa2c.png
typography_spectrum: 0.03950383048504591
layout_spectrum: 0
