typography_spectrum: 0.05285941972397268
color:
  saturation: 0.03791189705953002
  brandStrength: 0.03675346518866718
  lightness: 0.49380008527077734
  brandColors:
    - '#63A69F'
    - '#F2E1AC'
    - '#F2836B'
    - '#F2594B'
    - '#CD2C24'
  rhythmicContrast: 0.523912642383948
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7282301259692758
analytics:
  twitter: null
  google: null
  facebook: null
name: One Earth Community
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Login
    url: 'https://testing.thegrid.io/app'
    type: external
  - name: Join Us
    url: 'https://thegrid.io/#46294'
    type: external
  - name: Just Me & You
    url: 'http://thegrid.ai/justme/'
    type: external
  - name: My Country
    url: 'https://thegrid.ai/myallacrossamerica/'
    type: external
  - name: One Earth Community "the blog"
    url: 'http://thegrid.ai/one-earth-community-blog/'
    type: external
  - name: One Earth Challenged "the blog"
    url: 'https://thegrid.ai/one-earth-challanged/'
    type: external
  - name: Support
    url: 'https://thegridai.wufoo.com/forms/zkbqkdh11mytyz/'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: ''
description: ''
purpose: []
