layout_spectrum: 0.048057458363473415
typography_spectrum: 0.3997487830929458
color:
  saturation: 0.04809747030958533
  brandStrength: 0.22620330122299492
  rhythmicContrast: 0.28358261357061565
  brandColors:
    - '#105B63'
    - '#FFFAD5'
    - '#FFD34E'
    - '#DB9E36'
    - '#BD4932'
  lightness: 0.4290709423366934
title: we all live under the same sun
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: one earth...one community
navigation:
  - name: login
    url: 'https://testing.thegrid.io/app'
    type: external
  - name: sign up
    url: 'https://thegrid.io/#46294'
    type: external
  - name: me and you
    url: 'http://thegrid.ai/justme/'
    type: external
  - name: community blog
    url: 'http://thegrid.ai/one-earth-community-blog/'
    type: external
  - name: one earth...challenged
    url: 'https://thegrid.ai/one-earth-challanged/'
    type: external
  - name: 'My Country '
    url: 'https://thegrid.ai/myallacrossamerica/'
    type: external
analytics:
  twitter: null
  google: null
  facebook: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8bf933f8-5958-49bb-896a-9ad2d77a2cfa.png
cta:
  bucket: null
  version: null
  domain: null
name: One Earth Community
opengraph:
  image: null
  type: null
  appId: null
logo: null
