typography_spectrum: 0.40024
color:
  saturation: 0.8125
  brandStrength: 0
  lightness: 0.7986037
  brandColors:
    - '#c3c3c3'
    - '#393c35'
    - '#aa6430'
    - '#fdfee0'
    - '#fcef41'
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6245972
analytics:
  twitter: null
  google: null
  facebook: null
name: One Earth Community
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - id: 'https://testing.thegrid.io/app'
    url: 'https://testing.thegrid.io/app'
    name: Login
    type: external
  - id: 'https://thegrid.ai/one-earth-challanged/'
    url: 'https://thegrid.ai/one-earth-challanged/'
    name: 'One Earth Challenged '
    type: external
  - id: 'https://thegrid.ai/myallacrossamerica/'
    url: 'https://thegrid.ai/myallacrossamerica/'
    name: My Country
    type: external
  - id: 'http://thegrid.ai/justme/'
    url: 'http://thegrid.ai/justme/'
    name: Just Me & You
    type: external
  - id: 'https://thegridai.wufoo.com/forms/zkbqkdh11mytyz/'
    url: 'https://thegridai.wufoo.com/forms/zkbqkdh11mytyz/'
    name: Support
    type: external
  - id: 3988ef50-e6e1-4c4d-9a01-29e8e4611849
    url: 2016-07-19-one-earth-community.html
    name: Community and Family are the basis of our mission. Join Us.
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
