name: One Earth Community
favicon: null
layout_spectrum: 0.84932
typography_spectrum: 0.40024
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c3c3c3'
    - '#393c35'
    - '#aa6430'
    - '#fdfee0'
    - '#fcef41'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
